CREATE TABLE IF NOT EXISTS "main" (
	`nickname`	TEXT,
	`vorname`	TEXT,
	`nachname`	TEXT,
	`status`	TEXT,
	`adresse (straße)`	TEXT,
	`adresse (hausnummer)`	INTEGER,
	`adresse (postleitzahl)`	INTEGER,
	`adresse (ort)`	TEXT,
	`nummer (gebäude)`	INTEGER,
	`nummer (stube)`	INTEGER,
	`telefonnummer (mobil)`	INTEGER,
	`telefonnummer (festnetz)`	INTEGER,
	`e-mailadresse`	TEXT,
	`geburtsdatum`	TEXT,
	`verbrauch (02)`	INTEGER,
	`verbrauch (03)`	INTEGER,
	`verbrauch (05)`	INTEGER,
	`bezahlung (02)`	INTEGER,
	`bezahlung (03)`	INTEGER,
	`bezahlung (05)`	INTEGER,
	`bezahlung (fass)`	INTEGER,
	`restbetrag (sonstiges)`	INTEGER,
	`macks`	INTEGER,
	`member (einzahlung)`	INTEGER,
	`zahlungsart`	TEXT,
	`geklingelte bier (heute)`	INTEGER,
	`geklingelte bier (GdM)`	INTEGER,
	`tage (zahlungsverzug)`	INTEGER,
	`tage (abwesenheit)`	INTEGER,
	`liter (gesamt)`	INTEGER,
	`liter (PersHi)`	INTEGER,
	`liter (TdM)`	INTEGER,
	`liter (heute)`	INTEGER,
	`liter (Jahr)`	INTEGER,
	`guthaben`	INTEGER,
	`zahlungsrückstand`	INTEGER,
	`druck`	INTEGER,
	`tafel`	INTEGER,
	`mack (anzahl)`	INTEGER,
	`GdJ`	INTEGER,
	`(irgendwas mit macks)`	INTEGER,
	`kulanz`	INTEGER,
	`pay-tv`	INTEGER,
	`icq-uin`	INTEGER
);
